//go:build ignore

// Program gen writes greeting_gen.go; trivially deterministic so the
// goGenerate drift check can dogfood itself.
package main

import "os"

func main() {
	src := `// Code generated by gen.go; DO NOT EDIT.

package main

const greeting = "hello from go generate"
`
	if err := os.WriteFile("greeting_gen.go", []byte(src), 0o644); err != nil {
		panic(err)
	}
}
